version: "3"

services:
  simple-iot-server:
    build: .
    container_name: simple-iot-server
    volumes:
        - "./app/:/opt/app"
    environment:
      - PORT=8080
    ports:
      - 32121:8080